### ISSUE TITLE
Handle union of constants and types

### ISSUE THREAD

**Issue by brigand** [brigand/babel-plugin-flow-react-proptypes#1]
``` js
// This works
id: string | number
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.number
]);

// This works
id: 'foo' | 'bar'
PropTypes.oneOf([
  'foo',
  'bar'
]);

// This doesn't work yet
id: 'foo' | 'bar' | number
PropTypes.oneOfType([
  PropTypes.oneOf([
    'foo',
    'bar'
  ]),
  PropTypes.number,
]);
```

**Comment by harsimranb** [comment]
This doesn't work either:

```
const Enum = { START: 'start', FINISH: 'finish', BATMAN: 'batman' };
type: Enum.START | Enum.FINISH | Enum.BATMAN
```

Thoughts?

**Comment by brigand** [comment]
@harsimranb I don't have much time to work on this project right now, but I'd love a PR adding support for this 😄

**Comment by mhaas** [comment]
@brigand Shall we close this as well, or do you want to keep it open for the example given in: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/1#issuecomment-295379649

FWIW, I never had much luck using variables instead of literals as constants in flow, so I don't know if this works in flow to start with.
