### ISSUE TITLE
Insert require/import statements at the top

### ISSUE THREAD

**Issue by Andarist** [brigand/babel-plugin-flow-react-proptypes#159]
It's vital for libraries being published also in es6 modules format that they do not have any `require` calls in their source code. In addition it should be slightly quicker in commonjs environment to have this cached once per file instead of loading for each prop type.

**Comment by brigand** [comment]
Thanks for the report! I'd like to support this.

I think the ideal is to have the three options available: single `import`, single `require`, inline `require`.

The benefit of inline require is in combination with the `deadCode` option when the output is a common.js module. That's a recent addition; previously it was done as the easiest implementation.

My thought is a config option for targeting es6 modules, where we inject and `import`; otherwise we do a single `require`, but if `deadCode` is enabled, we do the current output.

This might be a little too tricky, so we could instead have a config option with values `"esm"`, `"require"`, `"inline-require"`.

**Comment by Andarist** [comment]
I was wondering about `deadCode` - it seems this is overlapping with `transform-react-remove-prop-types` but you describe how to use both at the same time and I'm a little bit confused about this.

Back on track - it would be super sweet to detect module format used by the file. `babel@7-beta` has a [helper module for inserting appropriate imports](https://github.com/babel/babel/tree/master/packages/babel-helper-module-imports), maybe we could check out its source code to see how it handles this. That way we wouldn't have to force configuration on the users and just use inline requires if the file is commonjs and `deadCode` is used. That's ofc just an idea, dunno if it's feasible. BTW also would be nice to prepare a working version with `babel@7`, I'm unsure though if it's possible to support both 6 and 7 in the same plugin's codebase.

**Comment by brigand** [comment]
We'll find a way to support 6 and 7 when 7 comes out as stable. I remember babel not supporting adding imports in plugins, not sure if they fixed that in the 6.x line.

I'm going to remove the mention of the remove-prop-types plugin once `deadCode` is fully implemented. We do some extra code generation besides the `.propTypes =` line, which also needs to be stripped.

We could try to detect modules, as long as there's an override switch. I don't really like the check they're doing there, which is the parser options (which defaults to it being an es module, at least in 6), or the `.mjs` file extension. Those could be right long term, but for now (if we can generate imports) I think we should add a config option, and pick a static default.

As we've added some config options, they've been disabled by default, but eventually I'm going to flip them to true by default. Going with that, I'd like to keep the change minimal until we get to that point.

So the current plan (very open to feedback):

 - figure out if we can add import/export declarations safely in babel 6
 - add a config option for inline require or top-of-file require
 - don't do anything special with this config option in combination with the `deadCode` option
 - if we can add import/export, add an 'esm' value to the config item enum, where we use import/export

[here]: https://github.com/babel/babel/blob/master/packages/babel-helper-module-imports/src/is-module.js

I don't know when I'll have time to work on this, but if you want to pick up one or more of the tasks, I'd love some help.

**Comment by Andarist** [comment]
> figure out if we can add import/export declarations safely in babel 6

Majority of react files should have React in scope to use jsx transform, it could be followed to its declaration to check which syntax was used. If you don't want to use babel's approach at the moment I don't really see any other approach than trying to guess based on the used syntax.

> if we can add import/export, add an 'esm' value to the config item enum, where we use import/export

Not sure if I know what do you mean.

> I don't know when I'll have time to work on this, but if you want to pick up one or more of the tasks, I'd love some help.

Having some other priorities in other OSS projects right now, but if I manage to do other stuff before you get to it, you can count on my help of course.

**Comment by billyjanitsch** [comment]
> We'll find a way to support 6 and 7 when 7 comes out as stable. I remember babel not supporting adding imports in plugins, not sure if they fixed that in the 6.x line.

Babel 6 supports this, as does Babel 7. [Here](https://github.com/vslinko/babel-plugin-react-require/blob/master/src/index.js#L22)'s an example.

> We could try to detect modules, as long as there's an override switch. I don't really like the check they're doing there, which is the parser options (which defaults to it being an es module, at least in 6), or the .mjs file extension.

I think their check makes sense; it's what most Babel 6 plugins are doing anyway. In fact, [many](https://github.com/vslinko/babel-plugin-react-require#example) are [opinionated](https://github.com/lodash/babel-plugin-lodash#faq) about _only_ supporting ESM. If someone wants a CJS build, they should have the [CJS module transform](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-modules-commonjs) somewhere in their pipeline (likely via [the env preset](https://github.com/babel/babel/tree/master/packages/babel-preset-env)).

(I see the rationale for supporting inline requires for the sake of dead code elimination, though. If you're aiming to keep the config maximally simple, you could use inline requires _only_ when `deadCode` is configured, and otherwise use ESM imports, removing the need for additional config entirely.)

**Comment by brigand** [comment]
Thanks for doing the research. Switching to ESM by default, and common.js when deadCode is enabled seems good.

**Comment by brigand** [comment]
Working on this here #162

cc @billyjanitsch
