### ISSUE TITLE
Import type - implementation guidelines?

### ISSUE THREAD

**Issue by ndreckshage** [brigand/babel-plugin-flow-react-proptypes#197]
Hi - I'm wondering how import types are supposed to work, and if we can provide guidelines for how we should get them working (for non-webpack projects).

Import types seem to work out of the box in webpack, but based on how things compile, its not clear to me what should happen. For example...

```
export type MyType = {
  a: number,
  b: string,
};
```

compiles to

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bpfrpt_proptype_MyType = undefined;
var _propTypes = require("prop-types");
var _propTypes2 = _interopRequireDefault(_propTypes);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var bpfrpt_proptype_MyType = {
  a: _propTypes2.default.number.isRequired,
  b: _propTypes2.default.string.isRequired
};

exports.bpfrpt_proptype_MyType = bpfrpt_proptype_MyType;
```

This makes sense, the rename to `bpfrpt_proptype_` to avoid name conflicts. However,

```
// @flow

import React from 'react';
import type { MyType } from 'types';

type Props = { aa: MyType }
const X = (props: Props) => <div />;

export default X;
```

compiles to

```
'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
var _react = require('react');
var _react2 = _interopRequireDefault(_react);
var _propTypes = require('prop-types');
var _propTypes2 = _interopRequireDefault(_propTypes);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var X = function X(props) {
  return _react2.default.createElement('div', null);
};

X.propTypes = {
  aa: function aa() {
    return (typeof MyType === 'function' ? _propTypes2.default.instanceOf(MyType).isRequired : _propTypes2.default.any.isRequired).apply(this, arguments);
  }
};

exports.default = X;
```

which refers to `MyType` directly. Is this a bug - shouldn't it be referencing `bpfrpt_proptype_MyType`?

However, webpack makes this work somehow.

The export type gets compiled to -
```
__webpack_require__.d(__webpack_exports__, "a", function() { return bpfrpt_proptype_MyType; });
```

And then imported as...

```
return (typeof __WEBPACK_IMPORTED_MODULE_1__types__["a" /* bpfrpt_proptype_MyType */] === 'function' ...
```

aliased to `a` rather than `bpfrpt_proptype_MyType`.

**Comment by brigand** [comment]
So with `from 'types'` we detect that it looks like an import from 'node_modules', and decide not to import the type, so it behaves like the import doesn't exist (you'd get the same output if you removed the type import).

If that's changed to `from './types'`, which looks like an import of your own source files (presumably also compiled by this plugin), then you get this:

```js
import React from "react";

const X = props => React.createElement("div", null);

X.propTypes = {
  aa: function() {
    return (typeof bpfrpt_proptype_MyType === "function"
      ? bpfrpt_proptype_MyType.isRequired
        ? bpfrpt_proptype_MyType.isRequired
        : bpfrpt_proptype_MyType
      : PropTypes.shape(bpfrpt_proptype_MyType).isRequired
    ).apply(this, arguments);
  }
};
export default X;
import { bpfrpt_proptype_MyType } from "./types";
import PropTypes from "prop-types";
```

The reason for the relative vs package import rule is the webpack will error if you try to import something that doesn't exist from an ESM. We had to add it when we started supporting the output you see above, with the import/export syntax being generated.

Your longer output examples are with the import/export syntax we generate being run through the official 'babel-plugin-transform-es2015-modules-commonjs' transform, which is why you get the require/exports.

You can get the plugin to produce require/exports code by enabling the 'deadCode' option, e.g. if you didn't want it to ever eliminate the code, it'd be:

```
"plugins": [["flow-react-proptypes", { "deadCode": "false" }]]
```

Hope that clarifies things a bit. Going to close this for now, but if you have ideas on improvements, please share.

**Comment by ndreckshage** [comment]
@brigand would you consider a PR that adds an option (default to current behavior) around https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/index.js#L629 to bypass the relative path regex / requirement?

We use a flat, haste-like module resolver, where filenames are guaranteed unique. Even in a webpack system, I think the current regex solution could potentially result in confusing behavior if aliases are used.
